# the deployment of jenkins slave, notice the mount of docker/kubectl command by hostPath
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-slave-${JENKINS_AGENT_NAME}
  namespace: cicd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: jenkins-slave
    spec:
      serviceAccount: jenkins
      containers:
      - name: jenkins-slave
        image: ${JENKINS_SLAVE_IMAGE}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /home/jenkins
          name: home
        - mountPath: /usr/bin/docker
          name: docker-cmd
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /usr/lib/x86_64-linux-gnu/libltdl.so.7
          name: libltdl-so
        - mountPath: /usr/bin/kubectl
          name: kubectl-cmd
        env:
          - name: JAVA_OPTS
            value: "-Duser.timezone=Asia/Shanghai"
          - name: JNLP_PROTOCOL_OPTS
            value: "-Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=false"
          - name: JENKINS_SECRET
            value: "${JENKINS_SECRET}"
          - name: JENKINS_URL
            value: "${JENKINS_URL}"
          - name: JENKINS_TUNNEL
            value: "${JENKINS_TUNNEL}"
          - name: JENKINS_AGENT_NAME
            value: "${JENKINS_AGENT_NAME}"
      volumes:
        - name: home
          hostPath:
            path: ${JENKINS_AGENT_VOLUME}
        - name: docker-cmd
          hostPath:
            path: /usr/bin/docker
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: libltdl-so
          hostPath:
            path: /usr/lib64/libltdl.so.7
        - name: kubectl-cmd
          hostPath:
            path: /usr/bin/kubectl
